name: Bundle
on:
    push:
        branches:
            - main

jobs:
    bundle:
        runs-on: ubuntu-latest
        steps:
            - uses: actions/checkout@v2

            - uses: actions/setup-node@v2
              with:
                  node-version: 19

            - run: node script/bundle.js

            - name: "setup git config"
              run: |
                  git config --global user.name "github-actions[bot]"
                  git config --global user.email "<>"

            - run: git add -A
            - run: git commit -m "[CI] Bundle Addons"
            - run: git push origin main
